plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/mustafaedis/Documents/GitHub/BLOOM"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/panel/*"
to = "/"
status = 404.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]